title: Lucy Malabar
url: "http://l777mbr.github.io"
baseurl: "/lucymalabar"

markdown: kramdown
#ins_logo: "./lse-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/l777mbr"
footer_text: "Page design by Lucy Malabar"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/lucymalabar/"
 - name: "CV"
   link: "CV.pdf"
 - name: "Contact"
   link: "contact"
